version: '3.9'

services:
  api-transferencia:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    volumes:
      - ./database:/app/database
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/database/contacorrente.db
